# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
  end

  config.vm.network  "forwarded_port",guest: 3306,host: 3306
  config.vm.network  "forwarded_port",guest: 27017,host: 27017
  config.vm.network  "forwarded_port",guest: 8161,host: 8161
  config.vm.network  "forwarded_port",guest: 61616,host: 61616
  config.vm.network  "forwarded_port",guest: 9000,host: 9000
  config.vm.network  "forwarded_port",guest: 9092,host:9092
  config.vm.network  "forwarded_port",guest: 6379,host:6379
  config.vm.provision "shell" do |s|
	  s.inline= "sudo apt-get update;sudo apt-get install docker.io -y;sudo apt-get install curl -y;sudo curl -sSL https://get.daocloud.io/daotools/set_mirror.sh | sh -s http://d17d4444.m.daocloud.io"
  end
  config.vm.provision "docker" do |d|
    d.run "mysql" ,image:"mysql:5.7",args:"-p 3306:3306 -e MYSQL\_ROOT\_PASSWORD=123456"
    d.run "mongoDb",image:"mongo",args:"-p 27017:27017 "
    d.run "redis",image:"redis",args:"-p 6379:6379"
	  # d.run "activemq",image:"webcenter/activemq",args:"-p 8161:8161 -p 61616:61616 "
  	# d.run "sonarqube",image:"sonarqube",args:"-p 9000:9000 -p 9092:9092"
  end

  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope= :box
  end
  
end
